/******************************************************************************
Finite State Machine
Project: ./fsm.dot
Description: das_fms

Generated by gv_fsm ruby gem, see https://rubygems.org/gems/gv_fsm
gv_fsm version 0.5.2
Generation date: 2026-05-17 23:02:29 +0200
Generated from: ./fsm.dot
The finite state machine has:
  4 states
  5 transition functions

******************************************************************************/

#include "fsm.h"
#include "adc.h"
#include "feedback-api.h"
#include "potentiometer-api.h"
#include "eagletrt-api.h"
// SEARCH FOR Your Code Here FOR CODE INSERTION POINTS!

// GLOBALS
// State human-readable names
const char *fsm_state_names[] = { "init", "idle", "error", "flash" };

// List of state functions
fsm_state_func_t *const fsm_state_table[FSM_NUM_STATES] = {
    fsm_do_init,  // in state init
    fsm_do_idle,  // in state idle
    fsm_do_error, // in state error
    fsm_do_flash, // in state flash
};

// Table of transition functions
transition_func_t *const fsm_transition_table[FSM_NUM_STATES][FSM_NUM_STATES] = {
    /* states:     init,  idle,          error,          flash      */
    /* init    */ { NULL, fsm_init_done, fsm_init_error, NULL },
    /* idle    */ { NULL, NULL, fsm_error_detected, fsm_start_flash },
    /* error   */ { NULL, NULL, NULL, NULL },
    /* flash   */ { NULL, fsm_flash_done, fsm_error_detected, NULL },
};

// Triggered event
fsm_event_data_t *fsm_fired_event = NULL;

/*** USER CODE BEGIN GLOBALS ***/

/*** USER CODE END GLOBALS ***/

// Function to check if an event has fired
bool fsm_is_event_triggered() {
    return fsm_fired_event != NULL;
}

// Function to trigger an event
void fsm_event_trigger(fsm_event_data_t *event) {
    if (fsm_fired_event != NULL)
        return;
    fsm_fired_event = event ? event : &(fsm_event_data_t){ .a = NULL };
}

/*  ____  _        _       
 * / ___|| |_ __ _| |_ ___ 
 * \___ \| __/ _` | __/ _ \
 *  ___) | || (_| | ||  __/
 * |____/ \__\__,_|\__\___|
 *                         
 *   __                  _   _                 
 *  / _|_   _ _ __   ___| |_(_) ___  _ __  ___ 
 * | |_| | | | '_ \ / __| __| |/ _ \| '_ \/ __|
 * |  _| |_| | | | | (__| |_| | (_) | | | \__ \
 * |_|  \__,_|_| |_|\___|\__|_|\___/|_| |_|___/
 */

// Function to be executed in state init
// valid return states: FSM_STATE_IDLE, FSM_STATE_ERROR
fsm_state_t fsm_do_init(fsm_state_data_t *data) {
    fsm_state_t next_state = FSM_STATE_IDLE;
    /* Your Code Here */
    EAGLETRT_API_UNUSED(data);

    if (feedback_api_init() != FEEDBACK_RC_OK) {
        next_state = FSM_STATE_ERROR;
    } else if (potentiometer_api_init() != POTENTIOMETER_RC_OK) {
        next_state = FSM_STATE_ERROR;
    } else {
        adc_start_dma_feedback();
        adc_start_dma_potentiometer();
        next_state = FSM_STATE_IDLE;
    }

    switch (next_state) {
        case FSM_STATE_IDLE:
        case FSM_STATE_ERROR:
            break;
        default:
            next_state = FSM_NO_CHANGE;
    }

    return next_state;
}

// Function to be executed in state idle
// valid return states: FSM_NO_CHANGE, FSM_STATE_IDLE, FSM_STATE_FLASH, FSM_STATE_ERROR
fsm_state_t fsm_do_idle(fsm_state_data_t *data) {
    fsm_state_t next_state = FSM_NO_CHANGE;
    /* Your Code Here */
    EAGLETRT_API_UNUSED(data);

    switch (next_state) {
        case FSM_NO_CHANGE:
        case FSM_STATE_IDLE:
        case FSM_STATE_FLASH:
        case FSM_STATE_ERROR:
            break;
        default:
            next_state = FSM_NO_CHANGE;
    }

    return next_state;
}

// Function to be executed in state error
// valid return states: FSM_NO_CHANGE, FSM_STATE_ERROR
fsm_state_t fsm_do_error(fsm_state_data_t *data) {
    fsm_state_t next_state = FSM_NO_CHANGE;
    /* Your Code Here */
    EAGLETRT_API_UNUSED(data);

    switch (next_state) {
        case FSM_NO_CHANGE:
        case FSM_STATE_ERROR:
            break;
        default:
            next_state = FSM_NO_CHANGE;
    }

    return next_state;
}

// Function to be executed in state flash
// valid return states: FSM_NO_CHANGE, FSM_STATE_IDLE, FSM_STATE_FLASH, FSM_STATE_ERROR
fsm_state_t fsm_do_flash(fsm_state_data_t *data) {
    fsm_state_t next_state = FSM_NO_CHANGE;
    /* Your Code Here */
    EAGLETRT_API_UNUSED(data);

    switch (next_state) {
        case FSM_NO_CHANGE:
        case FSM_STATE_IDLE:
        case FSM_STATE_FLASH:
        case FSM_STATE_ERROR:
            break;
        default:
            next_state = FSM_NO_CHANGE;
    }

    return next_state;
}

/*  _____                    _ _   _              
 * |_   _| __ __ _ _ __  ___(_) |_(_) ___  _ __   
 *   | || '__/ _` | '_ \/ __| | __| |/ _ \| '_ \
 *   | || | | (_| | | | \__ \ | |_| | (_) | | | | 
 *   |_||_|  \__,_|_| |_|___/_|\__|_|\___/|_| |_| 
 *                                                
 *   __                  _   _                 
 *  / _|_   _ _ __   ___| |_(_) ___  _ __  ___ 
 * | |_| | | | '_ \ / __| __| |/ _ \| '_ \/ __|
 * |  _| |_| | | | | (__| |_| | (_) | | | \__ \
 * |_|  \__,_|_| |_|\___|\__|_|\___/|_| |_|___/
 */

// This function is called in 1 transition:
// 1. from init to idle
void fsm_init_done(fsm_state_data_t *data) {
    /* Your Code Here */
    EAGLETRT_API_UNUSED(data);
}

// This function is called in 1 transition:
// 1. from init to error
void fsm_init_error(fsm_state_data_t *data) {
    /* Your Code Here */
    EAGLETRT_API_UNUSED(data);
}

// This function is called in 1 transition:
// 1. from idle to flash
void fsm_start_flash(fsm_state_data_t *data) {
    /* Your Code Here */
    EAGLETRT_API_UNUSED(data);
}

// This function is called in 2 transitions:
// 1. from idle to error
// 2. from flash to error
void fsm_error_detected(fsm_state_data_t *data) {
    /* Your Code Here */
    EAGLETRT_API_UNUSED(data);
}

// This function is called in 1 transition:
// 1. from flash to idle
void fsm_flash_done(fsm_state_data_t *data) {
    /* Your Code Here */
    EAGLETRT_API_UNUSED(data);
}

/*  ____  _        _        
 * / ___|| |_ __ _| |_ ___  
 * \___ \| __/ _` | __/ _ \
 *  ___) | || (_| | ||  __/ 
 * |____/ \__\__,_|\__\___| 
 *                          
 *                                              
 *  _ __ ___   __ _ _ __   __ _  __ _  ___ _ __ 
 * | '_ ` _ \ / _` | '_ \ / _` |/ _` |/ _ \ '__|
 * | | | | | | (_| | | | | (_| | (_| |  __/ |   
 * |_| |_| |_|\__,_|_| |_|\__,_|\__, |\___|_|   
 *                              |___/           
 */

fsm_state_t fsm_run_state(fsm_state_t cur_state, fsm_state_data_t *data) {

    /*** USER CODE BEGIN RUN_STATE ***/

    /*** USER CODE END RUN_STATE ***/

    fsm_event_data_t *prev_ev = fsm_fired_event;
    fsm_state_t new_state = fsm_state_table[cur_state](data);
    // Reset event status
    if (prev_ev != NULL)
        fsm_fired_event = NULL;
    if (new_state == FSM_NO_CHANGE)
        new_state = cur_state;
    transition_func_t *transition = fsm_transition_table[cur_state][new_state];
    if (transition)
        transition(data);
    return new_state;
}

/*** USER CODE BEGIN FUNCTIONS ***/

/*** USER CODE END FUNCTIONS ***/

#ifdef TEST_MAIN
#include <unistd.h>
int main() {
    fsm_state_t cur_state = FSM_STATE_INIT;
    do {
        cur_state = fsm_run_state(cur_state, NULL);
        sleep(1);
    } while (1);
    return 0;
}
#endif
