[platformio]
src_dir = .
include_dir = .
default_envs = release

[env:release]
platform = ststm32
upload_protocol = stlink
debug_tool = stlink
platform_packages = 
  toolchain-gccarmnoneeabi@=1.140201.0
monitor_speed = 115200

board = nucleo_g474re
board_build.ldscript = STM32G473XX_FLASH.ld

build_flags = 
    -ICore/Inc
    -IDrivers/CMSIS/Device/ST/STM32G4xx/Include
    -IDrivers/CMSIS/Include
    -IDrivers/STM32G4xx_HAL_Driver/Inc
    -DUSE_HAL_DRIVER
    -DSTM32G473xx
build_src_filter = 
    +<Core/Src/>
    +<Drivers/STM32G4xx_HAL_Driver/Src/>
    -<Drivers/STM32G4xx_HAL_Driver/Src/*_template.c>
    +<*.s>

check_tool = clangtidy
check_flags =
    clangtidy: --checks=-*,cert-*,clang-analyzer-*,bugprone-*,performance-*,readability-*
    clangtidy: --warnings-as-errors=clang-analyzer-*,bugprone-*
    clangtidy: --header-filter=^.*Core/(Inc|Src)/.+/[^/]+\.(c|h)$
    clangtidy: --system-headers=false
check_src_filters =
    -<**>
    +<Core/Src/>
    +<Core/Inc/>
